<?php

// BLOQUE DE CONFIGURACIÓN DE RUTAS
// DEFINE UNA CONSTANTE 'ROOT_PATH' QUE APUNTA A LA CARPETA RAÍZ DEL PROYECTO.
// ESTO ES PARA EL SERVIDOR (PHP) Y SE USA EN 'REQUIRE' O 'INCLUDE' PARA NUNCA PERDER LA UBICACIÓN DE LOS ARCHIVOS.
define('ROOT_PATH', __DIR__ . '/..');

// DETECTA SI EL SITIO SE EJECUTA EN UN SERVIDOR LOCAL ('LOCALHOST') O EN EL SERVIDOR DE PRODUCCIÓN (EL DOMINIO REAL).
if (strpos($_SERVER['HTTP_HOST'], 'localhost') !== false || strpos($_SERVER['HTTP_HOST'], '127.0.0.1') !== false) {
    // SI ES LOCAL, DEFINE 'BASE_URL' CON EL NOMBRE DE LA CARPETA DEL PROYECTO. ESTO ES PARA EL NAVEGADOR (CSS, JS, IMÁGENES).
    define('BASE_URL', '/SALUDCONNECT');
} else {
    // SI ES EN PRODUCCIÓN, LA RUTA BASE ES LA RAÍZ DEL DOMINIO, POR LO QUE SE DEJA VACÍA.
    define('BASE_URL', '');
}

// INICIA O REANUDA LA SESIÓN DEL USUARIO PARA PODER USAR VARIABLES DE SESIÓN (COMO $_SESSION).
session_start();

// BLOQUE DE CONEXIÓN A LA BASE DE DATOS
// INCLUYE EL ARCHIVO QUE CONTIENE LA LÓGICA DE CONEXIÓN.
require_once ROOT_PATH . '/include/conexion.php';

// CREA UNA NUEVA INSTANCIA DE LA CLASE 'DATABASE' Y ESTABLECE LA CONEXIÓN.
// LA VARIABLE '$con' QUEDA DISPONIBLE PARA SER USADA EN CUALQUIER PÁGINA QUE INCLUYA ESTE ARCHIVO.
$db = new Database();
$con = $db->conectar();
?>