<?php
// BLOQUE 1: CONFIGURACIÓN INICIAL
// INCLUYE EL ARCHIVO DE CONFIGURACIÓN GLOBAL.
// ESTO ES NECESARIO PARA TENER ACCESO A LA CONSTANTE 'BASE_URL' PARA LA REDIRECCIÓN.
require_once __DIR__ . '/config.php';


// BLOQUE 2: PROCESO DE CIERRE DE SESIÓN SEGURO
// EL ARCHIVO 'config.php' YA INICIA LA SESIÓN, POR LO QUE NO ES NECESARIO VOLVER A HACERLO.

// 1. LIMPIA TODAS LAS VARIABLES DE LA SESIÓN ACTUAL (COMO $_SESSION['doc_usu'], $_SESSION['id_rol'], ETC.).
$_SESSION = array();

// 2. SI EL SITIO UTILIZA COOKIES PARA LA SESIÓN, SE ASEGURA DE ELIMINAR LA COOKIE DEL NAVEGADOR DEL USUARIO.
// ESTO FUERZA AL NAVEGADOR A "OLVIDAR" LA SESIÓN ANTERIOR.
if (ini_get("session.use_cookies")) {
    $params = session_get_cookie_params();
    setcookie(session_name(), '', time() - 42000,
        $params["path"], $params["domain"],
        $params["secure"], $params["httponly"]
    );
}

// 3. DESTRUYE COMPLETAMENTE LA SESIÓN EN EL SERVIDOR, LIBERANDO LOS DATOS ALMACENADOS.
session_destroy();


// BLOQUE 3: REDIRECCIÓN FINAL
// REDIRIGE AL USUARIO A LA PÁGINA DE INICIO DE SESIÓN.
// SE UTILIZA 'BASE_URL' PARA CONSTRUIR UNA RUTA ABSOLUTA Y ROBUSTA, QUE FUNCIONARÁ
// CORRECTAMENTE TANTO EN EL ENTORNO LOCAL COMO EN EL SERVIDOR DE PRODUCCIÓN.
header("Location: " . BASE_URL . "/inicio_sesion.php");

// FINALIZA LA EJECUCIÓN DEL SCRIPT PARA ASEGURAR QUE NO SE PROCESE NADA MÁS DESPUÉS DE LA REDIRECCIÓN.
exit();
?>